spring.application.name=productjpa

#testing local computer
server.port=8083

#For railway
#server.port=${PORT:8080}

#testing railway
#spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}?${PGDATABASE}
#spring.datasource.username=${PGUSER}
#spring.datasource.password=${PGPASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

#PostgreSQL DB setting
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=root1234

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB